name: FIA Docs to Instagram

on:
  schedule:
    - cron: "17 * * * *"  # every hour at :17 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          BRANCH: main
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python main.py
