name: FIA PDF -> Instagram - hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with write)
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies (poppler & tesseract)
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils libpoppler-cpp-dev tesseract-ocr

      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run script
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        run: |
          python main.py

      - name: Push changes (if any)
        if: always()
        run: |
          git add posted.json || true
          git commit -m "Update posted.json from workflow" || echo "No changes to commit"
          git push || echo "Push failed"
